#Deployment
###controllers/pb-deploy.tml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mychart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: petclinic-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/petclinic"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '0.5'
            memory: '500Mi'
          requests:
            cpu: '0.5'
            memory: '500Mi'
        ports:
        - containerPort: 8080