apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080 # matches the container port
      protocol: TCP
      name: http
  selector:
    app: petclinic-app
