apiVersion: v1
kind: Service
metadata:
  name: {{ include "myChart.fullname" . }}
  labels:
    {{- include "myChart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080 # matches the container port
      protocol: TCP
      name: http
  selector:
    app: petclinic-app
